AllCops:
  Include:
    - "*.gemspec"
    - ".simplecov"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "tasks/*.rake"
Metrics/LineLength:
  Max: 120
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
