AllCops:
  Include:
    - "*.gemspec"
    - ".simplecov"
    - "Gemfile"
    - "Guardfile"
    - "Rakefile"
    - "tasks/*.rake"
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/VariableNumber:
  EnforcedStyle: snake_case
