addons:
  code_climate:
    repo_token:
      secure: E3bOUINqN9inAqw0EsziZGyTzwThdrVrPuiRN6LQYIc7tHWkJBY0UO+tNvpj0tQcF3ViBy8Lbi26W2Fy+y0FWR163AXxQ8wu6Tu21es+sIPUxxnr/WFbVc7CEsE68ExsfNUciHHa82xnHECYaSqpR7gLHeMW7wFksdQvcnNMr38=
before_install: rm coverage
gemfile: gemfiles/travis.rb
language: ruby
rvm:
- ruby-head
- 2.3
- 2.2
- 2.1
- 2.0
- 1.9.3
- 1.9.2
- 1.8.7
- jruby-head
- jruby-9
- jruby-1.7
- mruby
- rbx-2
- ree-1
