addons:
  code_climate:
    repo_token:
      secure: E3bOUINqN9inAqw0EsziZGyTzwThdrVrPuiRN6LQYIc7tHWkJBY0UO+tNvpj0tQcF3ViBy8Lbi26W2Fy+y0FWR163AXxQ8wu6Tu21es+sIPUxxnr/WFbVc7CEsE68ExsfNUciHHa82xnHECYaSqpR7gLHeMW7wFksdQvcnNMr38=
before_install: rm coverage
gemfile: gemfiles/travis.rb
language: ruby
matrix:
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/travis_1.8.7.rb
    - rvm: 1.9.2
      gemfile: gemfiles/travis_1.9.2.rb
    - rvm: 1.9.3
      gemfile: gemfiles/travis_1.9.3.rb
    - rvm: ree
      gemfile: gemfiles/travis_1.8.7.rb
rvm:
- 2.0.0-p648
- 2.1.10
- 2.2.7
- 2.3.4
- 2.4.0
- 2.4.1
- jruby-1.7.26
- jruby-9.1.5.0
- ruby-head
